version: "3"

volumes:
  squid-subsquid-network-db:

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb

    volumes:
      - squid-subsquid-network-db:/var/lib/postgresql/data:delegated
