volumes:
  squid-subsquid-network-db:

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: squid_token,squid_workers,squid_gateways,squid_vestings
    ports:
      - "${DB_PORT:-23798}:5432"
    shm_size: 1gb
    volumes:
      - squid-subsquid-network-db:/var/lib/postgresql/data:delegated
      - ./docker/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
