{
 "title": "Network metrics",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (\r\n    SELECT\r\n      count(*)\r\n    FROM\r\n      account\r\n    WHERE\r\n      balance > 0\r\n  ) as holders_count,\r\n  (\r\n    SELECT\r\n      sum(balance) / 1e18\r\n    FROM\r\n      account\r\n    WHERE\r\n      balance > 0\r\n  ) as total_supply,\r\n  (\r\n    SELECT\r\n      count(*)\r\n    FROM\r\n      transfer\r\n  ) as transfers_count"
    }
   ]
  },
  {
   "title": "Holders distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  type,\r\n  count(*)\r\nFROM\r\n  account\r\nWHERE\r\n  balance > 0\r\nGROUP BY\r\n  type\r\nORDER BY\r\n  count DESC"
    }
   ]
  },
  {
   "title": "Token distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH bonded as (\r\n  SELECT\r\n    'WORKER' as type,\r\n    sum(bond) / 1e18 as value\r\n  FROM\r\n    worker\r\n  WHERE\r\n    bond > 0\r\n),\r\ndelegated as (\r\n  SELECT\r\n    'DELEGATION' as type,\r\n    sum(deposit) / 1e18 as value\r\n  FROM\r\n    delegation\r\n  WHERE\r\n    deposit > 0\r\n),\r\nstaked as (\r\n  SELECT\r\n    'PORTAL' as type,\r\n    sum(amount) / 1e18 as value\r\n  from\r\n    gateway_stake\r\n  WHERE\r\n    amount > 0\r\n),\r\nbalances as (\r\n  SELECT\r\n    type,\r\n    sum(balance) / 1e18 as value\r\n  FROM\r\n    account\r\n  WHERE\r\n    balance > 0\r\n  GROUP BY\r\n    type\r\n)\r\nSELECT\r\n  a.type,\r\n  CASE\r\n    WHEN a.type = 'USER' THEN a.value - b.value - d.value - s.value\r\n    ELSE a.value\r\n  END as value\r\nFROM\r\n  balances as a\r\n  LEFT JOIN bonded as b ON a.type = 'USER'\r\n  LEFT JOIN delegated as d ON a.type = 'USER'\r\n  LEFT JOIN staked as s ON a.type = 'USER'\r\nUNION\r\nALL\r\nSELECT\r\n  *\r\nFROM\r\n  bonded\r\nUNION\r\nALL\r\nSELECT\r\n  *\r\nFROM\r\n  delegated\r\nUNION\r\nALL\r\nSELECT\r\n  *\r\nFROM\r\n  staked"
    }
   ]
  },
  {
   "title": "Top 100 holders",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT id as address, type, (balance) / 1e18 as balance FROM account WHERE balance > 0 ORDER BY balance DESC  LIMIT 100"
    }
   ]
  },
  {
   "title": "New workers",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT coalesce(name, peer_id) as name, created_at FROM worker ORDER BY created_at DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Recent activity",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, type, from_id as from, to_id as to, amount / 1e18 as amount FROM transfer WHERE \"timestamp\" BETWEEN  $__timeFrom() AND $__timeTo() ORDER BY timestamp DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Holders count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH daily_balances AS NOT MATERIALIZED (\r\n  SELECT\r\n    t.timestamp :: date as date,\r\n    account_id,\r\n    (\r\n      array_agg(\r\n        balance\r\n        ORDER BY\r\n          t.id DESC\r\n      )\r\n    ) [1] as balance,\r\n    SUM (\r\n      CASE\r\n        WHEN direction = 'FROM' THEN - t.amount\r\n        WHEN direction = 'TO' THEN t.amount\r\n        ELSE 0\r\n      END\r\n    ) as change\r\n  FROM\r\n    account_transfer\r\n    LEFT JOIN transfer as t ON transfer_id = t.id\r\n  GROUP BY\r\n    date,\r\n    account_id\r\n  ORDER BY\r\n    date\r\n),\r\ndaily_changes AS NOT MATERIALIZED (\r\n  SELECT\r\n    date,\r\n    SUM (\r\n      CASE\r\n        WHEN balance > 0\r\n        AND change = balance THEN 1\r\n        WHEN balance = 0 AND change < 0 THEN -1\r\n        ELSE 0\r\n      END\r\n    ) as daily_change\r\n  FROM\r\n    daily_balances\r\n  GROUP BY\r\n    date\r\n)\r\nSELECT\r\n  date,\r\n  daily_change,\r\n  SUM(daily_change) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN UNBOUNDED PRECEDING\r\n      AND CURRENT ROW\r\n  ) AS holders\r\nFROM\r\n  daily_changes\r\nORDER BY\r\n  date DESC"
    }
   ]
  },
  {
   "title": "Vesting value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date,\r\n  SUM(amount) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN UNBOUNDED PRECEDING\r\n      AND CURRENT ROW\r\n  ) as vesting\r\nFROM\r\n  (\r\n    SELECT\r\n      timestamp :: date as date,\r\n      sum(\r\n        CASE\r\n          WHEN t.type = 'TRANSFER' AND a.type = 'VESTING' THEN amount\r\n          WHEN t.type = 'RELEASE' THEN -amount\r\n          ELSE 0\r\n        END\r\n      ) / 1e18 as amount\r\n    FROM\r\n      transfer as t\r\n      JOIN account as a ON a.id = t.to_id\r\n    GROUP BY\r\n      date\r\n  ) as t\r\nORDER BY\r\n  date"
    },
    {
     "rawSql": "SELECT\r\n  date,\r\n  SUM(amount) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN UNBOUNDED PRECEDING\r\n      AND CURRENT ROW\r\n  ) as bonded\r\nFROM\r\n  (\r\n    SELECT\r\n      timestamp :: date as date,\r\n      sum(\r\n        CASE\r\n          WHEN t.type = 'DEPOSIT' AND af.type = 'VESTING' THEN amount\r\n          WHEN t.type = 'WITHDRAW' AND at.type = 'VESTING' THEN -amount\r\n          ELSE 0\r\n        END\r\n      ) / 1e18 as amount\r\n    FROM\r\n      transfer as t\r\n      JOIN account as af ON af.id = t.from_id\r\n      JOIN account as at ON at.id = t.to_id\r\n    WHERE worker_id IS NOT NULL\r\n    GROUP BY\r\n      date\r\n  ) as t\r\nORDER BY\r\n  date"
    },
    {
     "rawSql": "SELECT\r\n  date,\r\n  SUM(amount) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN UNBOUNDED PRECEDING\r\n      AND CURRENT ROW\r\n  ) as delegated\r\nFROM\r\n  (\r\n    SELECT\r\n      timestamp :: date as date,\r\n      sum(\r\n        CASE\r\n          WHEN t.type = 'DEPOSIT' AND af.type = 'VESTING' THEN amount\r\n          WHEN t.type = 'WITHDRAW' AND at.type = 'VESTING' THEN -amount\r\n          ELSE 0\r\n        END\r\n      ) / 1e18 as amount\r\n    FROM\r\n      transfer as t\r\n      JOIN account as af ON af.id = t.from_id\r\n      JOIN account as at ON at.id = t.to_id\r\n    WHERE delegation_id IS NOT NULL\r\n    GROUP BY\r\n      date\r\n  ) as t\r\nORDER BY\r\n  date"
    },
    {
     "rawSql": "SELECT\r\n  date,\r\n  SUM(amount) OVER (\r\n    ORDER BY\r\n      date ROWS BETWEEN UNBOUNDED PRECEDING\r\n      AND CURRENT ROW\r\n  ) as released\r\nFROM\r\n  (\r\n    SELECT\r\n      timestamp :: date as date,\r\n      sum(amount) / 1e18 as amount\r\n    FROM\r\n      transfer as t\r\n    WHERE type = 'RELEASE'\r\n    GROUP BY\r\n      date\r\n  ) as t\r\nORDER BY\r\n  date"
    }
   ]
  },
  {
   "title": "Locked value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "rawSql": "WITH filtered_events AS (\r\n  SELECT\r\n    t.timestamp :: date AS event_date,\r\n    CASE\r\n      WHEN t.type = 'DEPOSIT' THEN t.amount\r\n      WHEN t.type = 'WITHDRAW' THEN - t.amount\r\n      ELSE 0\r\n    END AS change_value\r\n  FROM\r\n    transfer t\r\n  WHERE\r\n    type in ('DEPOSIT', 'WITHDRAW')\r\n),\r\ndaily_changes AS (\r\n  SELECT\r\n    event_date,\r\n    SUM(change_value) / 1e18 AS daily_change\r\n  FROM\r\n    filtered_events\r\n  WHERE\r\n    event_date IS NOT NULL\r\n  GROUP BY\r\n    event_date\r\n)\r\nSELECT\r\n  event_date AS date,\r\n  daily_change,\r\n  SUM(daily_change) OVER (\r\n    ORDER BY\r\n      event_date\r\n  ) AS tvl\r\nFROM\r\n  daily_changes\r\nORDER BY\r\n  event_date;"
    }
   ]
  },
  {
   "title": "Active workers count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 35 },
   "targets": [
    {
     "rawSql": "WITH filtered_events AS (\r\n  SELECT \r\n    COALESCE(\r\n      wsc.timestamp,\r\n      LAG(wsc.timestamp) OVER (\r\n        PARTITION BY wsc.worker_id \r\n        ORDER BY wsc.block_number \r\n        ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING\r\n      )\r\n    )::date AS event_date,\r\n    CASE \r\n      WHEN wsc.status = 'ACTIVE' THEN 1\r\n      WHEN wsc.status = 'DEREGISTERED' THEN -1\r\n      ELSE 0\r\n    END AS change_value\r\n  FROM worker_status_change wsc\r\n  WHERE wsc.pending = false\r\n),\r\ndaily_changes AS (\r\n  SELECT \r\n    event_date,\r\n    SUM(change_value) AS daily_change\r\n  FROM filtered_events\r\n  WHERE event_date IS NOT NULL\r\n  GROUP BY event_date\r\n)\r\nSELECT \r\n  event_date AS date,\r\n  daily_change,\r\n  SUM(daily_change) OVER (\r\n    ORDER BY event_date\r\n    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\r\n  ) AS active_workers\r\nFROM daily_changes\r\nORDER BY event_date;\r\n"
    },
    {
     "rawSql": "SELECT\r\n  timestamp :: date as date,\r\n  count(DISTINCT worker_id) as online\r\nFROM\r\n  worker_metrics\r\nWHERE\r\n  uptime > 0\r\n  AND $__timeFilter(timestamp)\r\nGROUP BY\r\n  date"
    }
   ]
  },
  {
   "title": "Unique operators count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date,\r\n  change as daily_change,\r\n  SUM(change) OVER (\r\n    ORDER BY\r\n      date\r\n  )\r\nFROM\r\n  (\r\n    SELECT\r\n      date,\r\n      sum(\r\n        CASE\r\n          WHEN workers_count > 0\r\n          AND change = workers_count THEN 1\r\n          WHEN workers_count <= 0 AND change < 0 THEN -1\r\n          ELSE 0\r\n        END\r\n      ) as change\r\n    FROM\r\n      (\r\n        SELECT\r\n          date,\r\n          owner_id,\r\n          change,\r\n          sum(change) OVER (\r\n            PARTITION BY owner_id\r\n            ORDER BY\r\n              date\r\n          ) as workers_count\r\n        FROM\r\n          (\r\n            SELECT\r\n              timestamp :: date as date,\r\n              owner_id,\r\n              sum(\r\n                CASE\r\n                  WHEN status = 'REGISTERING' THEN 1\r\n                  WHEN status = 'WITHDRAWN' THEN -1\r\n                END\r\n              ) as change\r\n            FROM\r\n              (\r\n                SELECT\r\n                  wsc.id,\r\n                  wsc.timestamp,\r\n                  w.owner_id,\r\n                  wsc.status\r\n                FROM\r\n                  worker_status_change as wsc\r\n                  JOIN worker as w ON w.id = wsc.worker_id\r\n                WHERE\r\n                  wsc.status IN ('REGISTERING', 'WITHDRAWN')\r\n                ORDER BY\r\n                  wsc.id ASC\r\n              ) as events\r\n            GROUP BY\r\n              date,\r\n              owner_id\r\n          ) as a\r\n      ) as b\r\n    GROUP BY\r\n      date\r\n  ) as c\r\nORDER BY\r\n  date"
    }
   ]
  },
  {
   "title": "Delegations count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 43 },
   "targets": [
    {
     "rawSql": "WITH filtered_events AS (\r\n  SELECT \r\n    wsc.timestamp::date AS event_date,\r\n    CASE \r\n      WHEN wsc.status = 'ACTIVE' THEN 1\r\n      WHEN wsc.status = 'WITHDRAWN' THEN -1\r\n      ELSE 0\r\n    END AS change_value\r\n  FROM delegation_status_change wsc\r\n  WHERE wsc.pending = false\r\n),\r\ndaily_changes AS (\r\n  SELECT \r\n    event_date,\r\n    SUM(change_value) AS daily_change\r\n  FROM filtered_events\r\n  WHERE event_date IS NOT NULL\r\n  GROUP BY event_date\r\n)\r\nSELECT \r\n  event_date AS date,\r\n  daily_change,\r\n  SUM(daily_change) OVER (\r\n    ORDER BY event_date\r\n    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\r\n  ) AS delegations\r\nFROM daily_changes\r\nORDER BY event_date;\r\n"
    }
   ]
  },
  {
   "title": "Unique delegators count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date,\r\n  change as daily_change,\r\n  SUM(change) OVER (\r\n    ORDER BY\r\n      date\r\n  )\r\nFROM\r\n  (\r\n    SELECT\r\n      date,\r\n      sum(\r\n        CASE\r\n          WHEN workers_count > 0\r\n          AND change = workers_count THEN 1\r\n          WHEN workers_count <= 0 AND change < 0 THEN -1\r\n          ELSE 0\r\n        END\r\n      ) as change\r\n    FROM\r\n      (\r\n        SELECT\r\n          date,\r\n          owner_id,\r\n          change,\r\n          sum(change) OVER (\r\n            PARTITION BY owner_id\r\n            ORDER BY\r\n              date\r\n          ) as workers_count\r\n        FROM\r\n          (\r\n            SELECT\r\n              timestamp :: date as date,\r\n              owner_id,\r\n              sum(\r\n                CASE\r\n                  WHEN status = 'ACTIVE' THEN 1\r\n                  WHEN status = 'WITHDRAWN' THEN -1\r\n                  ELSE 0\r\n                END\r\n              ) as change\r\n            FROM\r\n              (\r\n                SELECT\r\n                  wsc.id,\r\n                  wsc.timestamp,\r\n                  w.owner_id,\r\n                  wsc.status\r\n                FROM\r\n                  delegation_status_change as wsc\r\n                  JOIN delegation as w ON w.id = wsc.delegation_id\r\n                WHERE\r\n                  wsc.status IN ('ACTIVE', 'WITHDRAWN')\r\n                ORDER BY\r\n                  wsc.id ASC\r\n              ) as events\r\n            GROUP BY\r\n              date,\r\n              owner_id\r\n          ) as a\r\n      ) as b\r\n    GROUP BY\r\n      date\r\n  ) as c\r\nORDER BY\r\n  date"
    }
   ]
  },
  {
   "title": "APR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp::date as day,\r\n  COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY apr), 0) as worker_apr,\r\n  COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY staker_apr), 0) as staker_apr\r\nFROM worker_reward \r\nWHERE \r\n  $__timeFilter(timestamp) \r\nGROUP BY day\r\nORDER BY day;"
    }
   ]
  },
  {
   "title": "Reward",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  day,\r\n  CAST(SUM(worker_reward) / 1e18 AS double precision) AS worker_reward,\r\n  CAST(SUM(delegation_reward) / 1e18 AS double precision) AS delegation_reward\r\nFROM (\r\n  SELECT\r\n    DATE_TRUNC('day', timestamp) AS day,\r\n    SUM(amount) AS worker_reward,\r\n    0 AS delegation_reward\r\n  FROM (SELECT * FROM worker_reward WHERE timestamp >= $__timeFrom() AND timestamp <= $__timeTo()) as wr\r\n  GROUP BY day\r\n\r\n  UNION ALL\r\n\r\n  SELECT\r\n    DATE_TRUNC('day', timestamp) AS day,\r\n    0 AS worker_reward,\r\n    SUM(amount) AS delegation_reward\r\n  FROM (SELECT * FROM delegation_reward WHERE timestamp >= $__timeFrom() AND timestamp <= $__timeTo()) as dr\r\n  GROUP BY day\r\n) sub\r\nGROUP BY day\r\nORDER BY day;"
    }
   ]
  },
  {
   "title": "Claimed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date,\r\n  sum (change) OVER (\r\n    ORDER BY\r\n      date\r\n  ) as claimed\r\nFROM\r\n(\r\n    SELECT\r\n      timestamp :: date as date,\r\n      sum(amount) / 1e18 as change\r\n    FROM\r\n      transfer\r\n    WHERE\r\n      type = 'CLAIM'\r\n    GROUP BY\r\n      date\r\n  ) as daily\r\nORDER BY\r\n  date"
    },
    {
     "rawSql": "SELECT\r\n  date,\r\n  sum (change) OVER (\r\n    ORDER BY\r\n      date\r\n  ) as rewarded\r\nFROM\r\n(\r\n    SELECT\r\n      timestamp :: date as date,\r\n      sum(amount + stakers_reward) / 1e18 as change\r\n    FROM\r\n      worker_reward\r\n    GROUP BY\r\n      date\r\n  ) as daily\r\nORDER BY\r\n  date"
    }
   ]
  },
  {
   "title": "Transfers count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT timestamp::date as date, type, count(*) FROM transfer WHERE $__timeFilter(timestamp) GROUP BY date, type ORDER BY date"
    }
   ]
  },
  {
   "title": "Unique accounts count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp :: date as date,\r\n  count(DISTINCT account_id)\r\nfrom\r\n  (\r\n    SELECT\r\n      timestamp,\r\n      from_id as account_id\r\n    FROM\r\n      transfer\r\n    UNION\r\n    ALL\r\n    SELECT\r\n      timestamp,\r\n      to_id as account_id\r\n    FROM\r\n      transfer\r\n  ) as t\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP BY\r\n  date\r\nORDER BY\r\n  date"
    }
   ]
  },
  {
   "title": "Queries count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp :: date as date,\r\n  sum(queries) as daily_change\r\nFROM\r\n  worker_metrics\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP BY\r\n  date"
    }
   ]
  },
  {
   "title": "Served data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp :: date as date,\r\n  sum(served_data) as daily_change\r\nFROM\r\n  worker_metrics\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP BY\r\n  date"
    }
   ]
  },
  {
   "title": "Stored data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  date,\r\n  sum(stored_data)\r\nFROM\r\n  (\r\n    SELECT\r\n      timestamp :: date as date,\r\n      worker_id,\r\n      max(stored_data) as stored_data\r\n    FROM\r\n      worker_metrics\r\n    WHERE\r\n      $__timeFilter(timestamp)\r\n    GROUP BY\r\n      date,\r\n      worker_id\r\n  ) as w\r\nGROUP BY\r\n  date"
    }
   ]
  }
 ]
}