export declare function createWorkerStatusId(workerId: string, blockNumber: number | bigint): string;
export declare function createDelegationStatusChangeId(delegationId: string, blockNumber: number | bigint): string;
export declare function createWorkerId(workerIndex: bigint): string;
export declare function createAccountId(address: string): string;
export declare function createGatewayOperatorId(address: string): string;
export declare function createDelegationId(workerId: string, accountId: string): string;
export declare function createCommitmentId(from: number | bigint, to: number | bigint): string;
export declare function createWorkerSnapshotId(workerId: string, snapshotIndex: number): string;
export declare function createEpochId(epochNumber: number): string;
export declare function createGatewayStakeId(operatorId: string, stakeIndex: number | bigint): string;
