#!/bin/bash

declare -A aliases

contracts_dir="./subsquid-network-contracts" 

rm -rf "./abi";
mkdir "./abi";

pnpm -C ${contracts_dir} install
pnpm -C ${contracts_dir} build

aliases=( [DistributedRewardsDistribution]=DistributedRewardDistribution )

for contract in "WorkerRegistration" "SQD" "Staking" "NetworkController" "RewardTreasury" "VestingFactory" "DistributedRewardsDistribution" "GatewayRegistry"; do
    folder=${aliases[$contract]:-$contract}
    cat "${contracts_dir}/packages/contracts/artifacts/$folder.sol/$contract.json" | jq -r .abi > "./abi/$contract.json";
done;
